@API_TOKEN_LOCAL = {{API_TOKEN}}
@API_BASE_URL_LOCAL = {{API_BASE_URL}}

### Register a new user
POST {{API_BASE_URL_LOCAL}}/user/register
Content-Type: application/json

{
    "name": "test1",
    "email": "test1@example.com",
    "password" :"Test@123"
}

### login a  user
POST {{API_BASE_URL_LOCAL}}/user/login
Content-Type: application/json

{
    "email": "test1@example.com",
    "password" :"Test@123"
}


### Get my profile
GET {{API_BASE_URL_LOCAL}}/user/my-profile
Authorization: Bearer {{API_TOKEN_LOCAL}}